server:
  port: 8082

jwt:
  # base64 encoded key
  secret: 9i3Bk8SJ3CfqIm+v9JJjHc5PGmqNmevaXDLYX4k0sW9hmhuvA6rTNWIM6uISlbVWcn28bMs+gY+P3LLzRytHMQ==
  # 30 min
  secs_to_expire_access: 1800
  # 30 days
  secs_to_expire_refresh: 2592000

oauth2:
  redirect-uris: http://localhost:3000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: OAUTH2_GOOGLE_CLIENT_ID
            client-secret: OAUTH2_GOOGLE_CLIENT_SECRET
            redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            client_id: OAUTH2_GITHUB_CLIENT_ID
            client_secret: OAUTH2_GITHUB_CLIENT_SECRET
            redirect_uri: "{baseUrl}/auth/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
